FROM openjdk:14-jdk-slim
LABEL author="Nemanja Kovac"
VOLUME ["/basketqube-ws"]
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENV MONGO_DATASOURCE_HOST localhost
EXPOSE 9055
ENTRYPOINT ["java","-jar","/app.jar"]

#FROM openjdk:11
#EXPOSE 8080
# jar file generated by maven install
#ADD target/basketqube-app.jar basketqube-app.jar
#ENTRYPOINT ["java","-jar","/basketqube-app.jar"]